name: Build Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AUTH_SERVER_IP: ${{ secrets.AUTH_SERVER_IP }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}

      - name: Setup rust toolchain
        run: rustup show

      - name: cargo fmt
        run: cargo fmt --all -- --check

      - name: cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # args: --all-features

      - name: cargo build
        run: cargo build --features "tls" --release --all-targets
